#!/bin/bash
set -xe

export GO111MODULE=""
export GOARCH="amd64"
export GOBIN=""
export GOCACHE="/root/.cache/go-build"
export GOENV="/root/.config/go/env"
export GOEXE=""
export GOFLAGS=""
export GOHOSTARCH="amd64"
export GOHOSTOS="linux"
export GOINSECURE=""
export GONOPROXY=""
export GONOSUMDB=""
export GOOS="linux"
export GOPATH="/root/go"
export GOPRIVATE=""
export GOPROXY="https://proxy.golang.org,direct"
export GOROOT="/snap/go/6274"
export GOSUMDB="sum.golang.org"
export GOTMPDIR=""
export GOTOOLDIR="/snap/go/6274/pkg/tool/linux_amd64"
export GCCGO="gccgo"
export AR="ar"
export CC="gcc"
export CXX="g++"
export CGO_ENABLED="1"
export GOMOD=""
export CGO_CFLAGS="-g -O2"
export CGO_CPPFLAGS=""
export CGO_CXXFLAGS="-g -O2"
export CGO_FFLAGS="-g -O2"
export CGO_LDFLAGS="-g -O2"
export PKG_CONFIG="pkg-config"
export GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build329514718=/tmp/go-build -gno-record-gcc-switches"

git checkout master && git pull origin master
cd webapp && make
