name: Deploy to EC2 Instances

on:
  push:
    branches: [master]

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: exec git checkout master
        uses: peterkimzz/aws-ssm-send-command@1.0.4
        id: ssm1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: |
            i-0210d14f68a978eba
            i-02921c61b29e01dd2
            i-0ce4a0f69269ac5c7

          working-directory: /home/isucon/isucon6q-20200906
          command: git checkout master
        
      - name: exec git pull origin master
        uses: peterkimzz/aws-ssm-send-command@1.0.4
        id: ssm2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: |
            i-0210d14f68a978eba
            i-02921c61b29e01dd2
            i-0ce4a0f69269ac5c7

          working-directory: /home/isucon/isucon6q-20200906
          command: git pull origin master 

      - name: exec make command
        uses: peterkimzz/aws-ssm-send-command@1.0.4
        id: ssm3
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: |
            i-0210d14f68a978eba
            i-02921c61b29e01dd2
            i-0ce4a0f69269ac5c7

          working-directory: /home/isucon/isucon6q-20200906/webapp
          command: make
