name: Deploy to EC2 Instances

on:
  push:
    branches: [master]

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: exec git checkout master
        uses: peterkimzz/aws-ssm-send-command@1.0.2
        id: ssm1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          working-directory: /home/isucon/isucon6q-20200906
          command: git checkout master
        
      - name: exec git pull origin master
        uses: peterkimzz/aws-ssm-send-command@1.0.2
        id: ssm2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          working-directory: /home/isucon/isucon6q-20200906
          command: git pull origin master 

      - name: exec make command
        uses: peterkimzz/aws-ssm-send-command@1.0.2
        id: ssm3
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          working-directory: /home/isucon/isucon6q-20200906/webapp
          command: make
